# Generated by Django 5.0.6 on 2024-06-25 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bomba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combustivel",
                    models.CharField(
                        choices=[("GAS", "Gasolina"), ("DIE", "Diesel")], max_length=3
                    ),
                ),
                ("capacidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantidade_atual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("preco_litro", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Abastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "combustivel",
                    models.CharField(
                        choices=[("GAS", "Gasolina"), ("DIE", "Diesel")], max_length=3
                    ),
                ),
                (
                    "litros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0.01)
                        ],
                    ),
                ),
                (
                    "imposto",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0),
                            django.core.validators.MaxValueValidator(limit_value=100),
                        ]
                    ),
                ),
                (
                    "valor_combustivel",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_imposto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bomba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.bomba"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bomba",
            name="tanque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.tanque"
            ),
        ),
    ]
